package Vista;

import Modelo.Conexion_MySQL;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author deivi
 */
public class Direccion extends javax.swing.JFrame {

    Conexion_MySQL CM = new Conexion_MySQL();
    Connection com = CM.getConexion();

    /**
     * Creates new form Direccion
     */
    public Direccion() {
        initComponents();
setIconImage(new ImageIcon(getClass().getResource("/Img/coding_html_programming.png")).getImage());
        this.setLocationRelativeTo(this);
 setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        
        MostrarDireccion();
    }
    //----------------------------------------------------------------------
    //---->>>Metodo Insertar Direccion.

    public void Direcion() {
        String Sql = "Insert Into direccion(,departamento,Ciudad,Carrera,Calle,Codigo_postal,Localidad, Barrio, empleados_Cedula) Values(?,?,?,?,?,?,?,?)";
        try {
            PreparedStatement ps = com.prepareStatement(Sql);
            ps.setString(2, txt_deprtamento.getText());
            ps.setString(3, txt_ciudad.getText());
            ps.setString(4, txt_carrera.getText());
            ps.setString(5, txt_calle.getText());
            ps.setString(6, txt_codigopostal.getText());
            ps.setString(7, txt_localida.getText());
            ps.setString(8, txt_barrio.getText());
           
            ps.execute();

            JOptionPane.showMessageDialog(null, "Registro exitoso");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error Direc " + e.getMessage());

        }

    }
    //---->>>Fin Metodo Direccion.
//------------------------------------------------------------------------

    //----->>>Metodo Mostrar Direccion.
    public void MostrarDireccion() {
        String[] Titulos = {"Departamento", "Ciudad", "Localidad", "Carrera", "Calle", "Barrio", "Cod postal", "Empleado"};
        String[] Registros = new String[8];
        DefaultTableModel modelo = new DefaultTableModel(null, Titulos);
        String Sql = "Select* From direcciones";
        try {

            try {

                Statement st = com.createStatement();
                ResultSet rs = st.executeQuery(Sql);

                while (rs.next()) {

                    Registros[0] = rs.getString("departamento");
                    Registros[1] = rs.getString("Ciudad");
                    Registros[2] = rs.getString("Localidad");
                    Registros[3] = rs.getString("Carrera");
                    Registros[4] = rs.getString("Calle");
                    Registros[5] = rs.getString("Barrio");
                    Registros[6] = rs.getString("Codigo_postal");
                    Registros[7] = rs.getString("Cedula");

                    modelo.addRow(Registros);

                }
                tbl_direccion.setModel(modelo);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Nose Pueden Cargar los Datosd " + e.getMessage());
            }

        } catch (Exception e) {
        }

    }
    //----->>>Fin Metodo Mostrar.

//---------------------------------------------------------------------------
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txt_codigopostal = new javax.swing.JTextField();
        txt_deprtamento = new javax.swing.JTextField();
        txt_ciudad = new javax.swing.JTextField();
        txt_carrera = new javax.swing.JTextField();
        txt_calle = new javax.swing.JTextField();
        txt_localida = new javax.swing.JTextField();
        txt_barrio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_menu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_direccion = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jlb_nombre = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jlb_deo = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jlb_cedula2 = new javax.swing.JLabel();
        jlb_sistema = new javax.swing.JLabel();
        jlb_emprea2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        ntn_limpiar1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Direccion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 3, 14), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Codigo postal:");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 130, -1));

        jLabel5.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Departamento:");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 130, -1));

        jLabel6.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Ciudad:");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 70, -1));

        jLabel7.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Carrera:");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 70, -1));

        jLabel8.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Localidad:");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, 90, -1));

        jLabel9.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Calle:");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 60, -1));

        jLabel31.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setText("Barrio:");
        jPanel4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 60, -1));
        jPanel4.add(txt_codigopostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 100, -1));
        jPanel4.add(txt_deprtamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 170, -1));
        jPanel4.add(txt_ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 180, -1));
        jPanel4.add(txt_carrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 90, -1));
        jPanel4.add(txt_calle, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 90, -1));
        jPanel4.add(txt_localida, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, 170, -1));

        txt_barrio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_barrioActionPerformed(evt);
            }
        });
        jPanel4.add(txt_barrio, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 180, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/mapa (1).png"))); // NOI18N
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 20, -1, -1));

        btn_menu.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btn_menu.setForeground(new java.awt.Color(0, 0, 0));
        btn_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cohete.png"))); // NOI18N
        btn_menu.setText("Ir a Menú Principal");
        btn_menu.setContentAreaFilled(false);
        btn_menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_menu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_menuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_menuMouseExited(evt);
            }
        });
        btn_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menuActionPerformed(evt);
            }
        });
        jPanel4.add(btn_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 110, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 160));

        tbl_direccion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbl_direccion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 1000, 420));

        jLabel17.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Nombre:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 70, -1));

        jlb_nombre.setForeground(new java.awt.Color(0, 0, 0));
        jlb_nombre.setText("Deivis de juesus");
        jPanel1.add(jlb_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 110, 20));

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Cedula:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 70, -1));

        jlb_deo.setForeground(new java.awt.Color(0, 0, 0));
        jlb_deo.setText("3065");
        jPanel1.add(jlb_deo, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 200, 40, 20));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setText("DO:");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, 37, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Empresa:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 70, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Dependencia:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 200, 100, -1));

        jlb_cedula2.setForeground(new java.awt.Color(0, 0, 0));
        jlb_cedula2.setText("1.002.474.228");
        jPanel1.add(jlb_cedula2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 80, 20));

        jlb_sistema.setForeground(new java.awt.Color(0, 0, 0));
        jlb_sistema.setText("Sistemas");
        jPanel1.add(jlb_sistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 200, 160, 20));

        jlb_emprea2.setForeground(new java.awt.Color(0, 0, 0));
        jlb_emprea2.setText("Multidimencionales");
        jPanel1.add(jlb_emprea2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 160, 20));

        jButton2.setBackground(new java.awt.Color(0, 0, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Actualizar");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 170, -1, -1));

        jButton1.setBackground(new java.awt.Color(102, 255, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Buscar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 270, 30));

        jButton5.setBackground(new java.awt.Color(0, 0, 255));
        jButton5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Modificar");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 170, 100, -1));

        ntn_limpiar1.setBackground(new java.awt.Color(0, 0, 255));
        ntn_limpiar1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        ntn_limpiar1.setForeground(new java.awt.Color(255, 255, 255));
        ntn_limpiar1.setText("Limpiar");
        ntn_limpiar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ntn_limpiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ntn_limpiar1ActionPerformed(evt);
            }
        });
        jPanel1.add(ntn_limpiar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 170, 90, -1));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/menu-abierto.png"))); // NOI18N

        jMenuItem2.setBackground(new java.awt.Color(0, 0, 204));
        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/trabajo-en-equipo.png"))); // NOI18N
        jMenuItem2.setText("Datos Personales");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem6.setBackground(new java.awt.Color(0, 0, 204));
        jMenuItem6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/planta-de-energia (1).png"))); // NOI18N
        jMenuItem6.setText("Datos Empresa");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem8.setBackground(new java.awt.Color(0, 0, 204));
        jMenuItem8.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cadena-de-valor (1).png"))); // NOI18N
        jMenuItem8.setText("Centros de costos");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_barrioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_barrioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_barrioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton2ActionPerformed

    private void ntn_limpiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ntn_limpiar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ntn_limpiar1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        Datos_personales P = new Datos_personales();
        P.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:

        Datos_empresa E = new Datos_empresa();
        E.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        Datos_CentrosCostos cos = new Datos_CentrosCostos();
        cos.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void btn_menuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menuMouseEntered
        btn_menu.setForeground(new Color(224, 255, 0 ));
    }//GEN-LAST:event_btn_menuMouseEntered

    private void btn_menuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menuMouseExited
        btn_menu.setForeground(new Color(0, 0, 0 ));
    }//GEN-LAST:event_btn_menuMouseExited

    private void btn_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menuActionPerformed
        Menu_principal M = new Menu_principal();
        M.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_menuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("W".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Direccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Direccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Direccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Direccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Direccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_menu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel jlb_cedula2;
    private javax.swing.JLabel jlb_deo;
    private javax.swing.JLabel jlb_emprea2;
    private javax.swing.JLabel jlb_nombre;
    private javax.swing.JLabel jlb_sistema;
    private javax.swing.JButton ntn_limpiar1;
    private javax.swing.JTable tbl_direccion;
    public javax.swing.JTextField txt_barrio;
    public javax.swing.JTextField txt_calle;
    public javax.swing.JTextField txt_carrera;
    public javax.swing.JTextField txt_ciudad;
    public javax.swing.JTextField txt_codigopostal;
    public javax.swing.JTextField txt_deprtamento;
    public javax.swing.JTextField txt_localida;
    // End of variables declaration//GEN-END:variables
}
