package Vista;

import Modelo.Conexion_MySQL;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.metal.MetalLookAndFeel;

/**
 *
 * @author deivi
 */
public class Loging extends javax.swing.JFrame {

    Conexion_MySQL CM = new Conexion_MySQL();
    Connection com = CM.getConexion();

    public Loging() {
        initComponents();
        setLocationRelativeTo(this);
        setTitle("Loging");
      
        setIconImage(new ImageIcon(getClass().getResource("/Img/usuario.png")).getImage());
    }
//-----------------------------------------------------------------------------------------------

    public void validarSecion() {
        Icon icono = new ImageIcon(getClass().getResource("/Img/coding_html_programming.png"));

        int resul = 0;
        String Contraseña = String.valueOf(txt_pass.getPassword());
        String Usuario = txt_usuario.getText();
     
        String sql = "select * from usuarios_sistema where Usuario='" + Usuario + "' AND Contraseña= '" + Contraseña + "'  ";

        try {
            Statement st = com.createStatement();
            ResultSet rs = st.executeQuery(sql);

            if (rs.next()) {

                resul = 1;

                if (resul == 1) {

                    JOptionPane.showMessageDialog(this, "!Hola " + txt_usuario.getText() + "  Bienvenido al Sistema¡", "Loging...", JOptionPane.INFORMATION_MESSAGE, icono);

                    Menu_principal form = new Menu_principal();
                    form.setVisible(true);
                    this.dispose();

                }

            } else {
                JOptionPane.showMessageDialog(null, "El usuario no existe");
            }

        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(null, "Error ");
        }

    }

//------------------------------------------------------------------------------------------------
    public void iniciar() {
        Icon icono = new ImageIcon(getClass().getResource("/Img/coding_html_programming.png"));
        String Usuario = txt_usuario.getText();
        String Clave = String.valueOf(txt_pass.getPassword());
        if ((Usuario.equals("deivis")) && (Clave.compareTo("23008606") == 0)) {

            JOptionPane.showMessageDialog(this, "!Hola " + txt_usuario.getText() + "  Bienvenido al Sitema¡", "Loging...", JOptionPane.INFORMATION_MESSAGE, icono);

            Menu_principal M = new Menu_principal();
            M.setVisible(true);
            this.dispose();

        } else if (Usuario.equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese Un Usuario");
        } else if (Clave.equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese una Clave ");
        } else {
            JOptionPane.showMessageDialog(null, "!El Usuario No Existe¡");

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_pass = new javax.swing.JPasswordField();
        txt_usuario = new javax.swing.JTextField();
        btn_cancelar = new javax.swing.JButton();
        btn_ingresar = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(250, 155));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 255, 189));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(new javax.swing.ImageIcon(getClass().getResource("/Img/Group 3.png")))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(250, 150));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel2.setText("Usuario:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, -1));

        jLabel3.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel3.setText("Password:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 90, -1));

        txt_pass.setForeground(new java.awt.Color(0, 0, 255));
        txt_pass.setBorder(null);
        txt_pass.setOpaque(true);
        txt_pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_passKeyPressed(evt);
            }
        });
        jPanel1.add(txt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 210, -1));

        txt_usuario.setForeground(new java.awt.Color(0, 0, 255));
        txt_usuario.setBorder(null);
        txt_usuario.setOpaque(true);
        txt_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usuarioActionPerformed(evt);
            }
        });
        jPanel1.add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 210, -1));

        btn_cancelar.setBackground(new java.awt.Color(0, 255, 189));
        btn_cancelar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btn_cancelar.setText("Borrar");
        btn_cancelar.setContentAreaFilled(false);
        btn_cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_cancelar.setOpaque(true);
        btn_cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_cancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_cancelarMouseExited(evt);
            }
        });
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 100, 20));

        btn_ingresar.setBackground(new java.awt.Color(0, 255, 189));
        btn_ingresar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btn_ingresar.setText("Ingresar");
        btn_ingresar.setContentAreaFilled(false);
        btn_ingresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ingresar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_ingresar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_ingresar.setOpaque(true);
        btn_ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ingresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ingresarMouseExited(evt);
            }
        });
        btn_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarActionPerformed(evt);
            }
        });
        btn_ingresar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_ingresarKeyPressed(evt);
            }
        });
        jPanel1.add(btn_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 100, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarActionPerformed
        // TODO add your handling code here:

        validarSecion();

    }//GEN-LAST:event_btn_ingresarActionPerformed

    private void btn_ingresarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_ingresarKeyPressed
        // TODO add your handling code here:


    }//GEN-LAST:event_btn_ingresarKeyPressed

    private void txt_passKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passKeyPressed
        // TODO add your handling code here:

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            validarSecion();

        }
    }//GEN-LAST:event_txt_passKeyPressed

    private void txt_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usuarioActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:

        txt_pass.setText("");
        txt_usuario.setText("");
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_ingresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ingresarMouseEntered
        btn_ingresar.setBackground(new Color(20, 30, 241));
        btn_ingresar.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_ingresarMouseEntered

    private void btn_cancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelarMouseEntered
        btn_cancelar.setBackground(new Color(20, 30, 241));
        btn_cancelar.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_cancelarMouseEntered

    private void btn_cancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelarMouseExited
        btn_cancelar.setBackground(new Color(0, 255, 189));
        btn_cancelar.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btn_cancelarMouseExited

    private void btn_ingresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ingresarMouseExited
        btn_ingresar.setBackground(new Color(0, 255, 189));
        btn_ingresar.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btn_ingresarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("W".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());

                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Loging().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_cancelar;
    public javax.swing.JButton btn_ingresar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    public javax.swing.JPasswordField txt_pass;
    public javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
